name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: chmod +x gradlew

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: aarch64-linux-android, armv7-linux-androideabi

      - name: Install Android NDK
        run: |
          NDK_VER=$(sed -n 's/^ndk = "\(.*\)"/\1/p' gradle/libs.versions.toml)
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "ndk;$NDK_VER"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: . -> target

      - run: sudo apt install -y gcc-multilib

      - name: Build native library
        run: |
          cargo xtask configure
          cargo xtask build --native-only

      - name: Build APK
        run: ./gradlew assembleStandardDebug --warning-mode all --stacktrace --info --no-configuration-cache 2>&1 | tee gradle.log

      - name: Upload gradle log
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: gradle-log
          path: gradle.log

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: welite-apk
          path: |
            app/build/outputs/apk/**/*.apk
